name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Check codestyle files in src
        run: git ls-files src/*.{c,h} | xargs clang-format -i --verbose && git diff --exit-code

      - name: Build application
        run: make

  test:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Check codestyle files in test
        run: git ls-files test/*.c | xargs clang-format -i --verbose && git diff --exit-code

      - name: Test application
        run: make test